In [4]:
import pandas as pd
import numpy as np
import re
from tqdm import tqdm
def str2float(x):
    return float(re.findall("\d+\.\d+", x)[0])

folder  = ".../T_models/"

# V_models

In [8]:
ls = ["train_avg_accuracy","train_std_accuracy","test_accuracy"]

final_mean = pd.DataFrame()
final_dataset_mean = pd.DataFrame()
folder = "V_models/repeat_new_"

final = pd.DataFrame()
final_dataset = pd.DataFrame()
for i in tqdm([i for i in range(4)]+[i for i in range(5,10)]+[i for i in range(11,15)]+[17,18,19]):
    result = pd.read_csv(folder +str(i)+".txt")
    result = result.sort_values(by=["train_avg_accuracy"], ascending=False)
    best_result = result.iloc[0]
    final = pd.concat([final, best_result[ls].T],axis=1)
    final_dataset = pd.concat([final_dataset, best_result[["train_dataset_accuracy","test_dataset_accuracy"]].T],axis=1)
final = final.T.reset_index(drop=True)
final_dataset = final_dataset.T.reset_index(drop=True)
final_mean = pd.concat([final_mean, pd.DataFrame(final.mean(),columns=[j]).T])
final_dataset_float = final_dataset.applymap(str2float)
final_dataset_mean = pd.concat([final_dataset_mean, pd.DataFrame(final_dataset_float.mean(),columns=[j]).T])
final


100%|██████████| 16/16 [00:00<00:00, 91.36it/s]


train_avg_accuracy train_std_accuracy test_accuracy
0            0.650871          0.0577851          0.78
1            0.635201          0.0728847       0.74359
2            0.648948          0.0371159      0.690476
3               0.675          0.0518411         0.375
4             0.60144           0.077732      0.533333
5            0.549612          0.0529668      0.577778
6            0.704413          0.0716699      0.428571
7            0.585513          0.0566123      0.448276
8            0.596341           0.144086      0.592593
9            0.543205           0.126865      0.637931
10           0.653659          0.0604366      0.607843
11           0.678543           0.101304      0.822581
12           0.579487           0.122058      0.180328
13           0.658537          0.0539901      0.392157
14           0.537652          0.0652701      0.634921
15           0.590476          0.0683462      0.717391

In [12]:
result = pd.read_csv("/local/wujimeng/code_jimeng/c_cte/GitHub/V_models/better from RF_tuned/repeat_2.txt")
result.columns

Index(['Unnamed: 0', 'n_estimators', 'min_weight_fraction_leaf',
       'min_samples_split', 'min_samples_leaf', 'max_samples', 'max_depth',
       'bootstrap', 'ah', 'ap', 'train_avg_accuracy', 'train_avg_recall',
       'train_avg_specificity', 'train_avg_f1', 'train_avg_precision',
       'train_std_accuracy', 'train_std_recall', 'train_std_specificity',
       'train_std_f1', 'train_std_precision', 'test_accuracy', 'test_recall',
       'test_specificity', 'test_f1', 'test_precision',
       'train_dataset_accuracy', 'test_dataset_accuracy'],
      dtype='object')

In [32]:
result.max_depth.unique()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
[i for i in np.linspace(start=0.1, stop=1, num=5)] + [i for i in np.linspace(start=0.2, stop=0.9, num=8)]

[0.1, 0.325, 0.55, 0.775, 1.0, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

In [ ]:
        "n_estimators": [int(x) for x in np.linspace(start=10, stop=100, num=5)]
        + [int(x) for x in np.linspace(start=2, stop=5, num=4)],
        "max_depth": [i for i in np.linspace(start=0.01, stop=1, num=5)]+ [i for i in range(2, 10, 1)]+ [i for i in range(10, 100, 20)]+ [None],
        "min_samples_leaf": [i for i in np.linspace(start=0.01, stop=0.5, num=5)]        + [i for i in np.linspace(start=0.1, stop=0.4, num=4)] + [1,2,4],
        "min_samples_split":[i for i in np.linspace(start=0.1, stop=1, num=5)] + [2,4,6],
        "max_samples": [i for i in np.linspace(start=0.1, stop=1, num=5)] + [i for i in np.linspace(start=0.2, stop=0.9, num=8)],


# T_median_ML

In [539]:
ls = ["train_avg_accuracy","train_std_accuracy","test_accuracy"]
folder  = "/local/wujimeng/code_jimeng/c_cte/GitHub/"
final_mean = pd.DataFrame()
final_dataset_mean = pd.DataFrame()
for j in ["T_models/T_median_ml/repeat_own_label_",]:

    final = pd.DataFrame()
    final_dataset = pd.DataFrame()

     for i in tqdm([i for i in range(4)]+[i for i in range(5,10)]+[i for i in range(11,15)]+[17,18,19]):

        result = pd.read_csv(folder + j+str(i)+".txt")
        result = result.sort_values(by=["train_avg_accuracy","test_accuracy"], ascending=False)
        best_result = result.iloc[0]

        final = pd.concat([final, best_result[ls].T],axis=1)
        final_dataset = pd.concat([final_dataset, best_result[["train_dataset_accuracy","test_dataset_accuracy"]].T],axis=1)
    final = final.T.reset_index(drop=True)
    final_dataset = final_dataset.T.reset_index(drop=True)
    final_mean = pd.concat([final_mean, pd.DataFrame(final.mean(),columns=[j]).T])
    final_dataset_float = final_dataset.applymap(str2float)
    final_dataset_mean = pd.concat([final_dataset_mean, pd.DataFrame(final_dataset_float.mean(),columns=[j]).T])
final
# final_dataset_float
# np.where(final!=final2)

train_avg_accuracy train_std_accuracy test_accuracy
0           0.775122          0.0912398      0.259259

# T_tuned_ML

In [ ]:
ls = ["train_avg_accuracy","train_std_accuracy","test_accuracy"]
folder  = "/local/wujimeng/code_jimeng/c_cte/GitHub/"
final_mean = pd.DataFrame()
final_dataset_mean = pd.DataFrame()
# for j in ["T_models/T_median_ml/repeat_own_label_new_",]:
for j in ["T_models/T_tuned_ml/repeat_own_label_",]:

    final = pd.DataFrame()
    final_dataset = pd.DataFrame()
    for i in tqdm([i for i in range(4)]+[i for i in range(5,10)]+[i for i in range(11,15)]+[17,18,19]):

        result = pd.read_csv(folder + j+str(i)+".txt")
        result = result.sort_values(by=["train_avg_accuracy","test_accuracy"], ascending=False)
        best_result = result.iloc[0]

        final = pd.concat([final, best_result[ls].T],axis=1)
        final_dataset = pd.concat([final_dataset, best_result[["train_dataset_accuracy","test_dataset_accuracy"]].T],axis=1)
    final = final.T.reset_index(drop=True)
    final_dataset = final_dataset.T.reset_index(drop=True)
    final_mean = pd.concat([final_mean, pd.DataFrame(final.mean(),columns=[j]).T])
    final_dataset_float = final_dataset.applymap(str2float)
    final_dataset_mean = pd.concat([final_dataset_mean, pd.DataFrame(final_dataset_float.mean(),columns=[j]).T])
final
# final_dataset_float
# np.where(final!=final2)

# T_num_ML

In [335]:
ls = ["train_avg_accuracy","train_std_accuracy","test_accuracy"]
folder  = "/local/wujimeng/code_jimeng/c_cte/GitHub/T_models/"
final_mean = pd.DataFrame()
final_dataset_mean = pd.DataFrame()
# for j in ["T_median_ml/repeat_own_label_new_",]:
# for j in ["T_tuned_ml/repeat_own_label_new_",]:
for j in ["T_num_ml/repeat_own_number_normal_"]:

    final = pd.DataFrame()
    final_dataset = pd.DataFrame()
#     for i in range(1):
    for i in tqdm([i for i in range(4)]+[i for i in range(5,10)]+[i for i in range(11,15)]+[17,18,19]):
        result = pd.read_csv(folder + j+str(i)+".txt")
        result = result.sort_values(by=["train_avg_accuracy","test_accuracy"], ascending=False)
        best_result = result.iloc[0]

        final = pd.concat([final, best_result[ls].T],axis=1)
        final_dataset = pd.concat([final_dataset, best_result[["train_dataset_accuracy","test_dataset_accuracy"]].T],axis=1)
    final = final.T.reset_index(drop=True)
    final_dataset = final_dataset.T.reset_index(drop=True)
    final_mean = pd.concat([final_mean, pd.DataFrame(final.mean(),columns=[j]).T])
    final_dataset_float = final_dataset.applymap(str2float)
    final_dataset_mean = pd.concat([final_dataset_mean, pd.DataFrame(final_dataset_float.mean(),columns=[j]).T])
final
# final_dataset_float
np.where(final!=final2)

100%|██████████| 16/16 [00:00<00:00, 123.85it/s]


(array([ 0,  0,  0,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  6,  6,  7,
         7,  8,  8,  8,  9, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15]),
 array([0, 1, 2, 0, 1, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 2,
        0, 1, 0, 1, 0, 1, 0, 1, 0, 1]))

# T_null => T_tuned, T_median

In [483]:
ls = ["train_dataset_accuracy","test_dataset_accuracy"]
folder = "/local/wujimeng/code_jimeng/c_cte/T_models/"

from tqdm import tqdm
# for j in ["T_null_full/repeat_own_label_"]:
for j in ["T_median/repeat_own_label_"]:
    final = pd.DataFrame()
    final_dataset = pd.DataFrame()
#     for i in tqdm(range(20)):
    for i in tqdm([i for i in range(4)]+[i for i in range(5,10)]+[i for i in range(11,15)]+[17,18,19]):
        result = pd.read_csv(folder + j+str(i)+".txt")
        result = result.sort_values(by=ls, ascending=False)
        best_result = result.iloc[0]

        final = pd.concat([final, best_result[ls].T],axis=1)
        final_dataset = pd.concat([final_dataset, best_result[["train_dataset_accuracy","test_dataset_accuracy"]].T],axis=1)
    final = final.T.reset_index(drop=True)
    final_dataset = final_dataset.T.reset_index(drop=True)
    final_mean = pd.concat([final_mean, pd.DataFrame(final.mean(),columns=[j]).T])
    final_dataset_float = final_dataset.applymap(str2float)
    final_dataset_mean = pd.concat([final_dataset_mean, pd.DataFrame(final_dataset_float.mean(),columns=[j]).T])
final_dataset_float2 = final_dataset_float

100%|██████████| 16/16 [00:00<00:00, 162.46it/s]


In [484]:
ls = ["train_dataset_accuracy","test_dataset_accuracy"]
folder = "/local/wujimeng/code_jimeng/c_cte/GitHub/T_models/"

from tqdm import tqdm
# for j in ["T_null/repeat_own_label_new_"]:
for j in ["T_median/repeat_own_label_"]:
    final = pd.DataFrame()
    final_dataset = pd.DataFrame()
#     for i in range(20):
#     for i in [14]:
    for i in tqdm([i for i in range(4)]+[i for i in range(5,10)]+[i for i in range(11,15)]+[17,18,19]):
        result = pd.read_csv(folder + j+str(i)+".txt")
        print(result)
        result = result.sort_values(by=ls, ascending=False)
        best_result = result.iloc[0]

        final = pd.concat([final, best_result[ls].T],axis=1)
        final_dataset = pd.concat([final_dataset, best_result[["train_dataset_accuracy","test_dataset_accuracy"]].T],axis=1)
    final = final.T.reset_index(drop=True)
    final_dataset = final_dataset.T.reset_index(drop=True)
    final_mean = pd.concat([final_mean, pd.DataFrame(final.mean(),columns=[j]).T])
    final_dataset_float = final_dataset.applymap(str2float)
    final_dataset_mean = pd.concat([final_dataset_mean, pd.DataFrame(final_dataset_float.mean(),columns=[j]).T])
final_dataset_float
np.where(final_dataset_float!=final_dataset_float2)

100%|██████████| 16/16 [00:00<00:00, 120.08it/s]

   Unnamed: 0  threshold train_dataset_accuracy test_dataset_accuracy
0           0  10.709906       0.5485 (113/206)           1.0 (50/50)
   Unnamed: 0  threshold train_dataset_accuracy test_dataset_accuracy
0           0  10.709906       0.6083 (132/217)        0.7949 (31/39)
   Unnamed: 0  threshold train_dataset_accuracy test_dataset_accuracy
0           0   6.692337       0.7056 (151/214)        0.4762 (20/42)
   Unnamed: 0  threshold train_dataset_accuracy test_dataset_accuracy
0           0   8.701122        0.765 (153/200)        0.3214 (18/56)
   Unnamed: 0  threshold train_dataset_accuracy test_dataset_accuracy
0           0  10.709906       0.5829 (123/211)        0.8889 (40/45)
   Unnamed: 0  threshold train_dataset_accuracy test_dataset_accuracy
0           0  10.709906       0.6825 (144/211)        0.4222 (19/45)
   Unnamed: 0  threshold train_dataset_accuracy test_dataset_accuracy
0           0    4.06962        0.628 (130/207)        0.4082 (20/49)
   Unnamed: 0  thres

(array([ 0,  1,  4,  5,  6,  7,  7,  9, 12, 12, 13, 13, 15]),
 array([0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0]))

## N_mul results

In [529]:
folder = "/local/wujimeng/code_jimeng/c_cte/GitHub/n_mul/"

for i in tqdm(range(1,4)):
    result = pd.read_csv(folder+"s_rasar_rasar_bi_" +str(i)+".txt")
    result = pd.read_csv(folder+"s_rasar_rasar_bi_" +str(i)+"_fullinfo.txt")


100%|██████████| 3/3 [00:00<00:00, 137.25it/s]


In [531]:
result

Unnamed: 0  n_estimators  min_samples_split  min_samples_leaf  max_depth  \
0           0           260                  2                 8         30   
1           0           260                  2                 8         30   
2           0           260                  2                 8         30   
3           0           260                  2                 8         30   

   class_weight  train_avg_accuracy  train_avg_recall  train_avg_specificity  \
0           NaN            0.937936               0.0                    1.0   
1           NaN            0.937936               0.0                    1.0   
2           NaN            0.937936               0.0                    1.0   
3           NaN            0.937936               0.0                    1.0   

   train_avg_f1  ...  train_std_f1  train_std_precision  test_accuracy  \
0           0.0  ...           0.0                  0.0       0.918919   
1           0.0  ...           0.0                  0.0       0.918919   
2           0.0  ...           0.0                  0.0       0.918919   
3           0.0  ...           0.0                  0.0       0.918919   

   test_recall  test_specificity  test_f1  test_precision  alpha_h  alpha_p  \
0          0.0               1.0      0.0             0.0     0.01     0.01   
1          0.0               1.0      0.0             0.0     0.01     1.00   
2          0.0               1.0      0.0             0.0     1.00     0.01   
3          0.0               1.0      0.0             0.0     1.00     1.00   

   num_neighbor  
0             3  
1             3  
2             3  
3             3  

[4 rows x 24 columns]