In [4]:
import pandas as pd
import numpy as np
import re
from tqdm import tqdm
def str2float(x):
    return float(re.findall("\d+\.\d+", x)[0])

folder  = ".../T_models/"

# V_models

In [8]:
ls = ["train_avg_accuracy","train_std_accuracy","test_accuracy"]

final_mean = pd.DataFrame()
final_dataset_mean = pd.DataFrame()
folder = "V_models/repeat_new_"

final = pd.DataFrame()
final_dataset = pd.DataFrame()
for i in tqdm([i for i in range(4)]+[i for i in range(5,10)]+[i for i in range(11,15)]+[17,18,19]):
    result = pd.read_csv(folder +str(i)+".txt")
    result = result.sort_values(by=["train_avg_accuracy"], ascending=False)
    best_result = result.iloc[0]
    final = pd.concat([final, best_result[ls].T],axis=1)
    final_dataset = pd.concat([final_dataset, best_result[["train_dataset_accuracy","test_dataset_accuracy"]].T],axis=1)
final = final.T.reset_index(drop=True)
final_dataset = final_dataset.T.reset_index(drop=True)
final_mean = pd.concat([final_mean, pd.DataFrame(final.mean(),columns=[j]).T])
final_dataset_float = final_dataset.applymap(str2float)
final_dataset_mean = pd.concat([final_dataset_mean, pd.DataFrame(final_dataset_float.mean(),columns=[j]).T])
final


100%|██████████| 16/16 [00:00<00:00, 91.36it/s]


train_avg_accuracy train_std_accuracy test_accuracy
0            0.650871          0.0577851          0.78
1            0.635201          0.0728847       0.74359
2            0.648948          0.0371159      0.690476
3               0.675          0.0518411         0.375
4             0.60144           0.077732      0.533333
5            0.549612          0.0529668      0.577778
6            0.704413          0.0716699      0.428571
7            0.585513          0.0566123      0.448276
8            0.596341           0.144086      0.592593
9            0.543205           0.126865      0.637931
10           0.653659          0.0604366      0.607843
11           0.678543           0.101304      0.822581
12           0.579487           0.122058      0.180328
13           0.658537          0.0539901      0.392157
14           0.537652          0.0652701      0.634921
15           0.590476          0.0683462      0.717391

In [12]:
result = pd.read_csv("/local/wujimeng/code_jimeng/c_cte/GitHub/V_models/better from RF_tuned/repeat_2.txt")
result.columns

Index(['Unnamed: 0', 'n_estimators', 'min_weight_fraction_leaf',
       'min_samples_split', 'min_samples_leaf', 'max_samples', 'max_depth',
       'bootstrap', 'ah', 'ap', 'train_avg_accuracy', 'train_avg_recall',
       'train_avg_specificity', 'train_avg_f1', 'train_avg_precision',
       'train_std_accuracy', 'train_std_recall', 'train_std_specificity',
       'train_std_f1', 'train_std_precision', 'test_accuracy', 'test_recall',
       'test_specificity', 'test_f1', 'test_precision',
       'train_dataset_accuracy', 'test_dataset_accuracy'],
      dtype='object')

In [32]:
result.max_depth.unique()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
[i for i in np.linspace(start=0.1, stop=1, num=5)] + [i for i in np.linspace(start=0.2, stop=0.9, num=8)]

[0.1, 0.325, 0.55, 0.775, 1.0, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

In [ ]:
        "n_estimators": [int(x) for x in np.linspace(start=10, stop=100, num=5)]
        + [int(x) for x in np.linspace(start=2, stop=5, num=4)],
        "max_depth": [i for i in np.linspace(start=0.01, stop=1, num=5)]+ [i for i in range(2, 10, 1)]+ [i for i in range(10, 100, 20)]+ [None],
        "min_samples_leaf": [i for i in np.linspace(start=0.01, stop=0.5, num=5)]        + [i for i in np.linspace(start=0.1, stop=0.4, num=4)] + [1,2,4],
        "min_samples_split":[i for i in np.linspace(start=0.1, stop=1, num=5)] + [2,4,6],
        "max_samples": [i for i in np.linspace(start=0.1, stop=1, num=5)] + [i for i in np.linspace(start=0.2, stop=0.9, num=8)],


# T_median_ML

In [539]:
ls = ["train_avg_accuracy","train_std_accuracy","test_accuracy"]
folder  = "/local/wujimeng/code_jimeng/c_cte/GitHub/"
final_mean = pd.DataFrame()
final_dataset_mean = pd.DataFrame()
for j in ["T_models/T_median_ml/repeat_own_label_",]:

    final = pd.DataFrame()
    final_dataset = pd.DataFrame()

     for i in tqdm([i for i in range(4)]+[i for i in range(5,10)]+[i for i in range(11,15)]+[17,18,19]):

        result = pd.read_csv(folder + j+str(i)+".txt")
        result = result.sort_values(by=["train_avg_accuracy","test_accuracy"], ascending=False)
        best_result = result.iloc[0]

        final = pd.concat([final, best_result[ls].T],axis=1)
        final_dataset = pd.concat([final_dataset, best_result[["train_dataset_accuracy","test_dataset_accuracy"]].T],axis=1)
    final = final.T.reset_index(drop=True)
    final_dataset = final_dataset.T.reset_index(drop=True)
    final_mean = pd.concat([final_mean, pd.DataFrame(final.mean(),columns=[j]).T])
    final_dataset_float = final_dataset.applymap(str2float)
    final_dataset_mean = pd.concat([final_dataset_mean, pd.DataFrame(final_dataset_float.mean(),columns=[j]).T])
final
# final_dataset_float
# np.where(final!=final2)

train_avg_accuracy train_std_accuracy test_accuracy
0           0.775122          0.0912398      0.259259

# T_tuned_ML

In [ ]:
ls = ["train_avg_accuracy","train_std_accuracy","test_accuracy"]
folder  = "/local/wujimeng/code_jimeng/c_cte/GitHub/"
final_mean = pd.DataFrame()
final_dataset_mean = pd.DataFrame()
# for j in ["T_models/T_median_ml/repeat_own_label_new_",]:
for j in ["T_models/T_tuned_ml/repeat_own_label_",]:

    final = pd.DataFrame()
    final_dataset = pd.DataFrame()
    for i in tqdm([i for i in range(4)]+[i for i in range(5,10)]+[i for i in range(11,15)]+[17,18,19]):

        result = pd.read_csv(folder + j+str(i)+".txt")
        result = result.sort_values(by=["train_avg_accuracy","test_accuracy"], ascending=False)
        best_result = result.iloc[0]

        final = pd.concat([final, best_result[ls].T],axis=1)
        final_dataset = pd.concat([final_dataset, best_result[["train_dataset_accuracy","test_dataset_accuracy"]].T],axis=1)
    final = final.T.reset_index(drop=True)
    final_dataset = final_dataset.T.reset_index(drop=True)
    final_mean = pd.concat([final_mean, pd.DataFrame(final.mean(),columns=[j]).T])
    final_dataset_float = final_dataset.applymap(str2float)
    final_dataset_mean = pd.concat([final_dataset_mean, pd.DataFrame(final_dataset_float.mean(),columns=[j]).T])
final
# final_dataset_float
# np.where(final!=final2)

# T_num_ML

In [335]:
ls = ["train_avg_accuracy","train_std_accuracy","test_accuracy"]
folder  = "/local/wujimeng/code_jimeng/c_cte/GitHub/T_models/"
final_mean = pd.DataFrame()
final_dataset_mean = pd.DataFrame()
# for j in ["T_median_ml/repeat_own_label_new_",]:
# for j in ["T_tuned_ml/repeat_own_label_new_",]:
for j in ["T_num_ml/repeat_own_number_normal_"]:

    final = pd.DataFrame()
    final_dataset = pd.DataFrame()
#     for i in range(1):
    for i in tqdm([i for i in range(4)]+[i for i in range(5,10)]+[i for i in range(11,15)]+[17,18,19]):
        result = pd.read_csv(folder + j+str(i)+".txt")
        result = result.sort_values(by=["train_avg_accuracy","test_accuracy"], ascending=False)
        best_result = result.iloc[0]

        final = pd.concat([final, best_result[ls].T],axis=1)
        final_dataset = pd.concat([final_dataset, best_result[["train_dataset_accuracy","test_dataset_accuracy"]].T],axis=1)
    final = final.T.reset_index(drop=True)
    final_dataset = final_dataset.T.reset_index(drop=True)
    final_mean = pd.concat([final_mean, pd.DataFrame(final.mean(),columns=[j]).T])
    final_dataset_float = final_dataset.applymap(str2float)
    final_dataset_mean = pd.concat([final_dataset_mean, pd.DataFrame(final_dataset_float.mean(),columns=[j]).T])
final
# final_dataset_float
np.where(final!=final2)

100%|██████████| 16/16 [00:00<00:00, 123.85it/s]


(array([ 0,  0,  0,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  6,  6,  7,
         7,  8,  8,  8,  9, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15]),
 array([0, 1, 2, 0, 1, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 2,
        0, 1, 0, 1, 0, 1, 0, 1, 0, 1]))

# T_null => T_tuned, T_median

In [483]:
ls = ["train_dataset_accuracy","test_dataset_accuracy"]
folder = "/local/wujimeng/code_jimeng/c_cte/T_models/"

from tqdm import tqdm
# for j in ["T_null_full/repeat_own_label_"]:
for j in ["T_median/repeat_own_label_"]:
    final = pd.DataFrame()
    final_dataset = pd.DataFrame()
#     for i in tqdm(range(20)):
    for i in tqdm([i for i in range(4)]+[i for i in range(5,10)]+[i for i in range(11,15)]+[17,18,19]):
        result = pd.read_csv(folder + j+str(i)+".txt")
        result = result.sort_values(by=ls, ascending=False)
        best_result = result.iloc[0]

        final = pd.concat([final, best_result[ls].T],axis=1)
        final_dataset = pd.concat([final_dataset, best_result[["train_dataset_accuracy","test_dataset_accuracy"]].T],axis=1)
    final = final.T.reset_index(drop=True)
    final_dataset = final_dataset.T.reset_index(drop=True)
    final_mean = pd.concat([final_mean, pd.DataFrame(final.mean(),columns=[j]).T])
    final_dataset_float = final_dataset.applymap(str2float)
    final_dataset_mean = pd.concat([final_dataset_mean, pd.DataFrame(final_dataset_float.mean(),columns=[j]).T])
final_dataset_float2 = final_dataset_float

100%|██████████| 16/16 [00:00<00:00, 162.46it/s]


In [484]:
ls = ["train_dataset_accuracy","test_dataset_accuracy"]
folder = "/local/wujimeng/code_jimeng/c_cte/GitHub/T_models/"

from tqdm import tqdm
# for j in ["T_null/repeat_own_label_new_"]:
for j in ["T_median/repeat_own_label_"]:
    final = pd.DataFrame()
    final_dataset = pd.DataFrame()
#     for i in range(20):
#     for i in [14]:
    for i in tqdm([i for i in range(4)]+[i for i in range(5,10)]+[i for i in range(11,15)]+[17,18,19]):
        result = pd.read_csv(folder + j+str(i)+".txt")
        print(result)
        result = result.sort_values(by=ls, ascending=False)
        best_result = result.iloc[0]

        final = pd.concat([final, best_result[ls].T],axis=1)
        final_dataset = pd.concat([final_dataset, best_result[["train_dataset_accuracy","test_dataset_accuracy"]].T],axis=1)
    final = final.T.reset_index(drop=True)
    final_dataset = final_dataset.T.reset_index(drop=True)
    final_mean = pd.concat([final_mean, pd.DataFrame(final.mean(),columns=[j]).T])
    final_dataset_float = final_dataset.applymap(str2float)
    final_dataset_mean = pd.concat([final_dataset_mean, pd.DataFrame(final_dataset_float.mean(),columns=[j]).T])
final_dataset_float
np.where(final_dataset_float!=final_dataset_float2)

100%|██████████| 16/16 [00:00<00:00, 120.08it/s]

   Unnamed: 0  threshold train_dataset_accuracy test_dataset_accuracy
0           0  10.709906       0.5485 (113/206)           1.0 (50/50)
   Unnamed: 0  threshold train_dataset_accuracy test_dataset_accuracy
0           0  10.709906       0.6083 (132/217)        0.7949 (31/39)
   Unnamed: 0  threshold train_dataset_accuracy test_dataset_accuracy
0           0   6.692337       0.7056 (151/214)        0.4762 (20/42)
   Unnamed: 0  threshold train_dataset_accuracy test_dataset_accuracy
0           0   8.701122        0.765 (153/200)        0.3214 (18/56)
   Unnamed: 0  threshold train_dataset_accuracy test_dataset_accuracy
0           0  10.709906       0.5829 (123/211)        0.8889 (40/45)
   Unnamed: 0  threshold train_dataset_accuracy test_dataset_accuracy
0           0  10.709906       0.6825 (144/211)        0.4222 (19/45)
   Unnamed: 0  threshold train_dataset_accuracy test_dataset_accuracy
0           0    4.06962        0.628 (130/207)        0.4082 (20/49)
   Unnamed: 0  thres

(array([ 0,  1,  4,  5,  6,  7,  7,  9, 12, 12, 13, 13, 15]),
 array([0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0]))

## N_mul results

In [37]:
folder = "/local/wujimeng/code_jimeng/c_cte/GitHub/n_mul/"

for i in tqdm(range(1,2)):
    result = pd.read_csv(folder+"s_rasar_rasar_bi_" +str(i)+".txt")
    result_full = pd.read_csv(folder+"s_rasar_rasar_bi_" +str(i)+"_fullinfo.txt")


100%|██████████| 1/1 [00:00<00:00, 100.55it/s]


In [42]:
result

Unnamed: 0  n_estimators  min_samples_split  min_samples_leaf  max_depth  \
0           0           440                  6                 2         25   

   class_weight  train_avg_accuracy  train_avg_recall  train_avg_specificity  \
0           NaN            0.710086          0.303352               0.941584   

   train_avg_f1  ...  train_std_f1  train_std_precision  test_accuracy  \
0      0.422361  ...      0.078285              0.05745       0.748778   

   test_recall  test_specificity   test_f1  test_precision   alpha_h  alpha_p  \
0     0.336127          0.946565  0.464389        0.750936  0.069519  0.78476   

   num_neighbor  
0             1  

[1 rows x 24 columns]

In [44]:
result_full.sort_values(["train_avg_accuracy"], ascending=False)

Unnamed: 0  n_estimators  min_samples_split  min_samples_leaf  max_depth  \
357           0           440                  6                 2         25   
79            0           440                  6                 2         25   
117           0           440                  6                 2         25   
319           0           440                  6                 2         25   
77            0           440                  6                 2         25   
..          ...           ...                ...               ...        ...   
721           0           440                  6                 2         25   
761           0           440                  6                 2         25   
783           0           440                  6                 2         25   
641           0           440                  6                 2         25   
643           0           440                  6                 2         25   

     class_weight  train_avg_accuracy  train_avg_recall  \
357           NaN            0.710086          0.303352   
79            NaN            0.705776          0.263332   
117           NaN            0.705477          0.260288   
319           NaN            0.705354          0.310698   
77            NaN            0.705237          0.265290   
..            ...                 ...               ...   
721           NaN            0.623726          0.338922   
761           NaN            0.622349          0.326044   
783           NaN            0.621870          0.345848   
641           NaN            0.621511          0.329671   
643           NaN            0.619534          0.334467   

     train_avg_specificity  train_avg_f1  ...  train_std_f1  \
357               0.941584      0.422361  ...      0.078285   
79                0.951492      0.351981  ...      0.140962   
117               0.954252      0.353544  ...      0.136386   
319               0.929395      0.427511  ...      0.069754   
77                0.950338      0.354608  ...      0.140262   
..                     ...           ...  ...           ...   
721               0.796402      0.397890  ...      0.006007   
761               0.801698      0.388103  ...      0.011795   
783               0.788346      0.401965  ...      0.011446   
641               0.796034      0.390563  ...      0.018823   
643               0.790081      0.392754  ...      0.018562   

     train_std_precision  test_accuracy  test_recall  test_specificity  \
357             0.057450       0.748778     0.336127          0.946565   
79              0.085795       0.720261     0.220453          0.959823   
117             0.102534       0.718903     0.193630          0.970671   
319             0.061392       0.736828     0.279128          0.956207   
77              0.095604       0.713743     0.192791          0.963439   
..                   ...            ...          ...               ...   
721             0.043136       0.658066     0.346186          0.807553   
761             0.052517       0.644758     0.335289          0.793090   
783             0.044888       0.667300     0.341157          0.823624   
641             0.052166       0.650462     0.311819          0.812776   
643             0.051160       0.654264     0.306790          0.820812   

      test_f1  test_precision   alpha_h   alpha_p  num_neighbor  
357  0.464389        0.750936  0.069519  0.784760             1  
79   0.338046        0.724518  0.012743  1.000000             1  
117  0.308617        0.759868  0.016238  0.784760             1  
319  0.407339        0.753394  0.054556  1.000000             1  
77   0.303831        0.716511  0.012743  0.784760             1  
..        ...             ...       ...       ...           ...  
721  0.396163        0.463004  0.784760  0.010000             1  
761  0.379507        0.437158  1.000000  0.010000             1  
783  0.399215        0.481087  1.000000  0.143845             1  
641  0.366322    